# Generated by Django 3.1.1 on 2020-09-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gjob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPost1',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryHeader1', models.CharField(max_length=150)),
                ('BookPost1Image1', models.ImageField(default='', upload_to='Index/images')),
                ('BookPost1Image2', models.ImageField(default='', upload_to='Index/images')),
                ('BookPost1Image3', models.ImageField(default='', upload_to='Index/images')),
            ],
        ),
        migrations.CreateModel(
            name='BookPost2',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryHeader2', models.CharField(max_length=150)),
                ('BookPost2Image1', models.ImageField(default='', upload_to='Index/images')),
                ('BookPost2Image2', models.ImageField(default='', upload_to='Index/images')),
                ('BookPost2Image3', models.ImageField(default='', upload_to='Index/images')),
            ],
        ),
        migrations.CreateModel(
            name='BookPost3',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryHeader3', models.CharField(max_length=150)),
                ('BookPost3Image1', models.ImageField(default='', upload_to='Index/images')),
                ('BookPost3Image2', models.ImageField(default='', upload_to='Index/images')),
                ('BookPost3Image3', models.ImageField(default='', upload_to='Index/images')),
            ],
        ),
    ]
