# Generated by Django 3.1.1 on 2020-09-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwingTradePost',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=150)),
                ('stockname', models.CharField(max_length=150)),
                ('sector', models.CharField(max_length=150)),
                ('priceandaction', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
