# Generated by Django 3.1.1 on 2020-09-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0002_previousswingtrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCard',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('cardheading', models.CharField(max_length=150)),
                ('stockname1', models.CharField(max_length=150)),
                ('stockname2', models.CharField(max_length=150)),
                ('stockname3', models.CharField(max_length=150)),
                ('stockname4', models.CharField(max_length=150)),
                ('stockname5', models.CharField(max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
