# Generated by Django 3.1.1 on 2020-09-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0004_stockcard_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermBet',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=150)),
                ('stockname', models.CharField(max_length=150)),
                ('intrinscivalue', models.CharField(max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
