# Generated by Django 3.1.1 on 2020-09-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceNews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideNewsPics',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('SideNewsImage1', models.ImageField(default='', upload_to='Index/images')),
                ('SideNewsImage2', models.ImageField(default='', upload_to='Index/images')),
                ('SideNewsImage3', models.ImageField(default='', upload_to='Index/images')),
            ],
        ),
    ]
