# Generated by Django 3.1.1 on 2020-09-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceNews', '0002_sidenewspics'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderNewsPics',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('HeaderNewsImage1', models.ImageField(default='', upload_to='Index/images')),
                ('HeaderNewsImage2', models.ImageField(default='', upload_to='Index/images')),
                ('HeaderNewsImage3', models.ImageField(default='', upload_to='Index/images')),
            ],
        ),
    ]
