# Generated by Django 3.1.1 on 2020-09-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexValue',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('niftyvalue', models.TextField()),
                ('sensexvalue', models.TextField()),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
