# Generated by Django 3.1.1 on 2020-09-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_indexvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDetails',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('stockofweekshare', models.TextField()),
                ('stockofweeksharedetail', models.TextField()),
                ('stockofweektimeStamp', models.DateTimeField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('stockofmonthshare', models.TextField()),
                ('stockofmonthsharedetail', models.TextField()),
                ('stockofmonthtimeStamp', models.DateTimeField(blank=True)),
                ('hrhrshare', models.TextField()),
                ('hrhrsharedetail', models.TextField()),
                ('hrhrsharetimeStamp', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
