# Generated by Django 3.1.1 on 2020-09-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_stockdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageStockContact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('useremail', models.CharField(max_length=50)),
                ('userphone', models.CharField(max_length=15)),
            ],
        ),
    ]
